[[social]]
    identifier = "YouTube"
    name       = "YouTube"
    url        = "https://github.com/CaiJimmy/hugo-theme-stack"

    [social.params]
        icon = "brand-youTube"

[[social]]
    identifier = "bilibili"
    name       = "bilibili"
    url        = "https://space.bilibili.com/162179329?spm_id_from"

    [social.params]
        icon = "brand-bilibili"
